linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple

linters-settings:
  goimports:
    local-prefixes: memodroid

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
